### ISSUE TITLE
Database Schma

### ISSUE THREAD

**Issue by DanMorriss** [DanMorriss/MenTool#11]
As a **developer** I need to **create a SQL database schema** so that **data can be added by the user**.

**Acceptance Criteria:**
- Use Django's built in user model so a class for mood with the following:
- [x] User
- [x] Date
- [x] Mood on a scale of 1-5
- [x] Comment (optional)

**Comment by tomdu3** [comment]
Up and running.
I changed scale 0-4, but with the categorical values
    VERY_HAPPY = 0
    HAPPY = 1
    MEH = 2
    SAD = 3
    VERY_SAD = 4
    MOOD_CHOICES = (
        (VERY_HAPPY, 'Very Happy'),
        (HAPPY, 'Happy'),
        (MEH, 'Meh'),
        (SAD, 'Sad'),
        (VERY_SAD, 'Very Sad'),
    )

**Comment by tomdu3** [comment]
OK
